// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// add_rcpp
double add_rcpp(double x, double y);
RcppExport SEXP TestRcpp_add_rcpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    __result = Rcpp::wrap(add_rcpp(x, y));
    return __result;
END_RCPP
}
// add_rcpp_default
double add_rcpp_default(double x, double y);
RcppExport SEXP TestRcpp_add_rcpp_default(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    __result = Rcpp::wrap(add_rcpp_default(x, y));
    return __result;
END_RCPP
}
