# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_rcpp <- function(x, y) {
    .Call('TestRcpp_add_rcpp', PACKAGE = 'TestRcpp', x, y)
}

add_rcpp_default <- function(x, y = 1) {
    .Call('TestRcpp_add_rcpp_default', PACKAGE = 'TestRcpp', x, y)
}

