# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_array_definition <- function(x) {
    .Call(`_lookup_parse_array_definition`, x)
}

find_function_end <- function(x, start = 0L) {
    .Call(`_lookup_find_function_end`, x, start)
}

